### PR TITLE
Support for the latest CS-Cart version

### PR DESCRIPTION
**Pull request by Woet**
- Overhauled the README to match LSWS
- Moved the add-on files to a folder called `cscart/`
- Used ESI to cache CSRF token privately
- Removed Varnish configuration fields
- Improved .htaccess

### CODE REVIEW

**Comment by dangtrungluong** [comment]
It show <esi:remove >1df03aea8f45b57f95aaecddbb20e9e9</esi:remove>

Storage Path: /home/$HOSTNAME/lscache/

I see exist files at Storage Path

**Comment by dangtrungluong** [comment]
It show < esi:remove>1df03aea8f45b57f95aaecddbb20e9e9</esi:remove>

Storage Path: /home/$VH_ROOT/lscache/

I see exist files at Storage Path

**Comment by Woet** [comment]
@dangtrungluong Are you using LiteSpeed Web Server (LSWS) or OpenLiteSpeed (OLS)? Do you have ESI enabled?

**Comment by dangtrungluong** [comment]
i have test and work with: https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:no-plugin-advanced:esi-support
i'm using Free Starter

**Comment by Woet** [comment]
@dangtrungluong can you please confirm you appended the htaccess to the correct .htaccess file?
`cat full-page-cache-addon/htaccess_lscache >> /your/cscart/installation/.htaccess`

If so, could you please send me the contents of your .htaccess file as well as a link to your website?

**Comment by dangtrungluong** [comment]
Hi, I'm reinstall OS and worked!
Thanks,

**Comment by dangtrungluong** [comment]
It not working with multiple currency, languages
>> index.php?dispatch=_no_page&currency=USD
>> index.php?dispatch=_no_page&sl=en

**Comment by Woet** [comment]
Hi @dangtrungluong,

Please send me a link to the website and explain what you mean by "it's not working". Does it cache incorrectly? Or does it not cache at all?

**Comment by dangtrungluong** [comment]
It working, but enable multiple currency, languages > will be return index.php?dispatch=_no_page&currency=USD
index.php?dispatch=_no_page&sl=en


.htaccess
`DirectoryIndex index.php


<IfModule LiteSpeed>
	RewriteEngine on
	CacheLookup on
	RewriteCond %{REQUEST_URI}   !(esi\.php|api\.php|admin\.php|login|cart/|checkout/|checkout\-customer\-info/|checkout\-summary/|orders/|compare/|wishlist/)
	RewriteCond %{QUERY_STRING}  !dispatch=(checkout\..+|orders\..+|wishlist\..+|product_features\.add_product|product_features\.clear_list|product_features\.delete_product|product_features\.delete_feature|product_features\.compare|auth\.login_form)
	RewriteCond %{HTTP_COOKIE}   !disable_cache=Y
	RewriteRule .* - [E=cache-control:max-age=900,E=esi_on:1]

	RewriteCond %{REQUEST_URI}   !esi\.php
	RewriteCond %{HTTP_COOKIE}   sid_customer_
	RewriteRule .* - [E=HTTP_X_HAS_SESSION:true,E=cache-control:vary=hassession,E=esi_on:1]
</IfModule>

<IfModule mod_deflate.c>
	AddOutputFilterByType DEFLATE application/javascript application/x-javascript text/javascript application/json
	AddOutputFilterByType DEFLATE application/x-font application/x-font-opentype application/x-font-otf application/x-font-truetype application/x-font-ttf font/opentype font/otf font/ttf application/x-woff application/x-font-woff
	AddOutputFilterByType DEFLATE text/css text/html text/plain

	<IfModule mod_headers.c>
		BrowserMatch ^Mozilla/4 gzip-only-text/html
		BrowserMatch ^Mozilla/4\.0[678] no-gzip
		BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
		Header append Vary User-Agent
	</IfModule>
</IfModule>

<IfModule mod_headers.c>
	<FilesMatch "\.(ttf|ttc|otf|eot|woff|css|png|gif|ico|jpe?g)$">
		Header set Access-Control-Allow-Origin "*"
	</FilesMatch>
</IfModule>

<IfModule mod_expires.c>
	<FilesMatch "\.(jpg|jpeg|png|gif|tiff|bmp|js|css)$">
	    ExpiresActive on
	    ExpiresDefault "access plus 2 weeks"
	</FilesMatch>
</IfModule>

<IfModule mod_headers.c>
	<filesMatch "\.(gif|png|jpg|jpeg|ico|js|css)$">
		Header set Cache-Control "max-age=1209600"
	</filesMatch>
</IfModule>


<IfModule mod_rewrite.c>
RewriteEngine on

RewriteRule ^init.php$ - [F,L,NC]

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(favicon|apple-touch-icon-|homescreen-|firefox-icon-|coast-icon-|mstile-).*\.(png|ico)$ - [R=404,NC,L]

RewriteCond %{REQUEST_URI} ^api/(.*)$ [or]
RewriteCond %{REQUEST_URI} .*/api/(.*)$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .*api/(.*)$ api.php?_d=$1 [L,QSA]

RewriteCond %{REQUEST_URI} \.(png|gif|ico|swf|jpe?g|js|css|ttf|svg|eot|woff|yml|xml)$ [NC,or]
RewriteCond %{REQUEST_URI} store_closed.html$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*?)\/(.*)$ $2 [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L,QSA]

</IfModule>

<IfModule mod_php5.c>
    php_flag zlib.output_compression Off
</IfModule>

`
Link: songhanh.vn

**Pull request merged**
